version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./frontend:/frontend
    environment:
      - FLASK_ENV=development
      - XAI_API_KEY=  #ton_cle_api_anthropic  # Ton API Key ici

